export type WeatherPoint = { time: string; label: string; temp: number; feelsLike: number; description: string; icon: string; rainProbability: number; rainMm: number; windKmh: number };
export type WeatherPayload = { location: { name: string; country: string; lat: number; lon: number }; current: WeatherPoint & { humidity: number; visibilityKm: number; pressure: number; uvIndex: number }; hourly: WeatherPoint[]; daily: Array<{ date: string; label: string; min: number; max: number; icon: string; description: string; rainProbability: number; rainMm: number }>; alerts: Array<{ level: 'watch' | 'advisory' | 'info'; title: string; message: string; time: string }>; fetchedAt: string };
const API = 'https://api.openweathermap.org/data/2.5';
function key() { const value = process.env.OPENWEATHER_API_KEY; if (!value) throw new Error('OPENWEATHER_API_KEY is not configured'); return value; }
function iconFor(code: number) { if (code >= 200 && code < 300) return '⛈️'; if (code >= 300 && code < 600) return '🌧️'; if (code >= 600 && code < 700) return '❄️'; if (code >= 700 && code < 800) return '🌫️'; if (code === 800) return '☀️'; return '⛅'; }
function label(date: Date, options?: Intl.DateTimeFormatOptions) { return new Intl.DateTimeFormat('en-IN', { timeZone: 'Asia/Kolkata', ...options }).format(date); }
async function getJson(path: string) { const response = await fetch(path); if (!response.ok) throw new Error('OpenWeather returned ' + response.status); return response.json(); }
export async function geocode(query: string) { const places = await getJson('https://api.openweathermap.org/geo/1.0/direct?q=' + encodeURIComponent(query) + '&limit=5&appid=' + key()); return places.map((place: any) => ({ name: place.name, country: place.country, state: place.state, lat: place.lat, lon: place.lon })); }
export async function getWeather(lat: number, lon: number, name = 'Your location'): Promise<WeatherPayload> {
  if (!Number.isFinite(lat) || !Number.isFinite(lon)) throw new Error('Valid coordinates are required');
  const query = 'lat=' + lat + '&lon=' + lon + '&appid=' + key() + '&units=metric';
  const [current, forecast] = await Promise.all([getJson(API + '/weather?' + query), getJson(API + '/forecast?' + query)]);
  const points = forecast.list as any[];
  const hourly = points.slice(0, 8).map((item) => ({ time: item.dt_txt, label: label(new Date(item.dt * 1000), { hour: 'numeric' }), temp: Math.round(item.main.temp), feelsLike: Math.round(item.main.feels_like), description: item.weather[0].description, icon: iconFor(item.weather[0].id), rainProbability: Math.round((item.pop || 0) * 100), rainMm: Number((item.rain?.['3h'] || 0).toFixed(1)), windKmh: Math.round((item.wind.speed || 0) * 3.6) }));
  const grouped = new Map<string, any[]>(); points.forEach((item) => { const day = label(new Date(item.dt * 1000), { weekday: 'short', month: 'short', day: 'numeric' }); grouped.set(day, [...(grouped.get(day) || []), item]); });
  const daily = Array.from(grouped.entries()).slice(0, 5).map(([dayLabel, items]) => { const midday = items.reduce((best, item) => Math.abs(new Date(item.dt * 1000).getHours() - 12) < Math.abs(new Date(best.dt * 1000).getHours() - 12) ? item : best, items[0]); return { date: midday.dt_txt, label: dayLabel, min: Math.round(Math.min(...items.map((item) => item.main.temp_min))), max: Math.round(Math.max(...items.map((item) => item.main.temp_max))), icon: iconFor(midday.weather[0].id), description: midday.weather[0].description, rainProbability: Math.round(Math.max(...items.map((item) => (item.pop || 0) * 100))), rainMm: Number(items.reduce((sum, item) => sum + (item.rain?.['3h'] || 0), 0).toFixed(1)) }; });
  const rain24h = Number(hourly.reduce((sum, item) => sum + item.rainMm, 0).toFixed(1)); const maxRainProbability = Math.max(...hourly.map((item) => item.rainProbability), 0); const alerts: WeatherPayload['alerts'] = [];
  if (rain24h >= 25 || maxRainProbability >= 80) alerts.push({ level: 'watch', title: 'Rain likely soon', message: rain24h > 0 ? rain24h + ' mm may fall in the next 24 hours. Plan outdoor and field work around the rain window.' : 'There is a high chance of rain in the next 24 hours.', time: 'Next 24 hours' });
  if (current.wind?.speed * 3.6 >= 35) alerts.push({ level: 'advisory', title: 'Strong wind advisory', message: 'Winds may reach ' + Math.round(current.wind.speed * 3.6) + ' km/h. Secure loose items and avoid spraying crops.', time: 'Now' });
  if (!alerts.length) alerts.push({ level: 'info', title: 'No immediate rain alert', message: 'No heavy rain signal is visible in the next 24 hours. Keep checking before weather-sensitive work.', time: 'Next 24 hours' });
  return { location: { name, country: current.sys?.country || '', lat, lon }, current: { time: new Date(current.dt * 1000).toISOString(), label: 'Now', temp: Math.round(current.main.temp), feelsLike: Math.round(current.main.feels_like), description: current.weather[0].description, icon: iconFor(current.weather[0].id), rainProbability: hourly[0]?.rainProbability || 0, rainMm: Number((current.rain?.['1h'] || 0).toFixed(1)), windKmh: Math.round(current.wind.speed * 3.6), humidity: current.main.humidity, visibilityKm: Number(((current.visibility || 0) / 1000).toFixed(1)), pressure: current.main.pressure, uvIndex: 0 }, hourly, daily, alerts, fetchedAt: new Date().toISOString() };
}
